### ISSUE TITLE
How to discriminate boolean and date from server point of view?

### ISSUE THREAD

**Issue by patrice-conil** [camaraproject/SimSwap#10]
Hi @DT-DawidWroblewski, Best wishes for 2023, 
As you use only one scope to call userinfo ... As a server developper, how can I determine the reply type to send back?

Patrice

**Comment by DT-DawidWroblewski** [comment]
Hi @patrice-conil ! Wishing you all the best in 2023!

As a developer you receive a reply type according to your declaration that happens during onboarding process. 

Due to legal concerns, it is required that developer/service provider delivers a statement regarding
- what is the use case for API consumption
- how consent acquisition process is designed, along with consent wording
- what is preferred reply type (boolean or timestamp)

according to onboarding declaration API is being set up in a way that satisfies developer/SP.

**Comment by patrice-conil** [comment]
Hi @DT-DawidWroblewski, 
So, as a server developer, I have to maintain a link between the subscription portal and the simswap service to check what was subscribed during the onboarding process (Because I need this information to forge the reply).
Why not to use two different scopes to discriminate the returned info?

**Comment by DT-DawidWroblewski** [comment]
Hi @patrice-conil !
this might be an option - let's discuss it on our next call :)
