### ISSUE TITLE
Update commonalities glossary with subproject relevant terms

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/SimSwap#11]
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by rartych** [comment]
In order to integrate the common glossary in Commonalities it is needed to provide the first version of subproject relevant terms by **15th of March** - it can be placed in this issue within the following table:
| Term      | Description | Usage in API (Parameter/Field) | Alternative developer-friendly terms |
| ------------ | ----------- | ----------- |  ----------- |
| | | | |
