### ISSUE TITLE
Add UTC precision for SIMswap date.

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#43]
**Problem description**
What is the time zone for the date time provided by the SIM swap get date?

**Possible evolution**
Indicate in the description that we use UTC (Coordinated Universal time)
I guess this in implicit right now but better to be explicit?

@monamok @DT-DawidWroblewski  WDYT?

**Comment by monamok** [comment]
We usually for these kind of parameters use descriptions like this for example:

_Timestamp of latest SIM swap performed, in ISO-8601 extended local date format. Time-offset from UTC may be used to match the local time._

but besides being date-time we don't force it. How do you suggest to have it as explicit? With a pattern?

**Comment by bigludo7** [comment]
@monamok Thanks. No I did no plan to change the attribute formatting. My proposal was just to update the description to make it explicit.

**Comment by monamok** [comment]
Thank you @bigludo7. The example I added was more kind of recommendation without saying explicitly that it must be UTC, It's more focused on ISO-8601 standard. Do you think using UTC must be part of the guideline? I'm not sure if there are more APIs over CAMARA that use date-time parameters.

P.D. I opened this issue https://github.com/camaraproject/SimSwap/issues/42 last week in order to improve and align the documentation with the guidlines. Once decided, we can include this point in a common PR for both issues.

**Comment by bigludo7** [comment]
@monamok : I will propose a very small update in the design guideline document to indicate that datetime attribute has to use UTC (if nothing explicitly else).

**Comment by bigludo7** [comment]
https://github.com/camaraproject/WorkingGroups/issues/240   ;)

**Comment by monamok** [comment]
Thank you @bigludo7

**Comment by gregory1g** [comment]
Why it must be UTC? "ISO 8601" includes timezone as well, so the API client does not need to have any assumptions on its side.

**Comment by DT-DawidWroblewski** [comment]
AP - take this item to commonalities
