### ISSUE TITLE
SimSwap API release version scope 0.4.0

### ISSUE THREAD

**Issue by DT-DawidWroblewski** [camaraproject/SimSwap#54]
**Problem description**
discuss the scope to be included in the Release

**Expected action**
create a first release of SIM Swap API
**v0.4.1.**

**Additional context**

**Comment by hdamker** [comment]
As stated in https://github.com/camaraproject/SimSwap/pull/53#pullrequestreview-1629372469: I propose to create a base release (with initial Changelog) now for v0.4.1 with the content of the repository and then agree on the changes which has to be done for a release v0.5.0.

**Comment by gregory1g** [comment]
what stops us from ver 1.0?
I see:
- auth scope naming (there are ongoing discussions in communalities and Identity)
- representation of never

Events are not necessary needed for 1.0, I think

**Comment by fernandopradocabrillo** [comment]
@DT-DawidWroblewski @bigludo7 
I've seen that a release has been made for v0.4.0. What is this release exactly? 
The code in the branch seems like a cherry pick from different versions mixed together. But if you dowload the release, the code is the 0.5.0-wip.
I think we are very close to a stable 0.5.0, maybe we can discuss a release in that version, I don't think we have any big open issues that would prevent us from doing so.
But in my opinion this one is not correct and should be removed.

**Comment by hdamker** [comment]
@fernandopradocabrillo you were right, the release v0.4.0 pointed not the right commit. It's deleted and created now with the right target commit.

Background is that there is a specific commit of v0.4.0 (https://github.com/camaraproject/SimSwap/commit/6843563242709cc82c6d5ea3cd6d484f14e44bfe) which multiple operators have agreed to implement in their markets. We took this commit as starting point of the branch release-0.4.0, correct the security schema (so that it has three-legged only, as agreed), and added a changelog and an update to README.md to this branch. And finally tagged this as release-0.4.0.

The PR #55 is now about reviewing this release and add the information about it into main (CHANGELOG.md and README.md update).

**Comment by gregory1g** [comment]
question: what benefits github release brings over simple tagging given commit as v0.4.0?

**Comment by gregory1g** [comment]
shouldn't this change be cherry picket to 0.4.X branch? To isolate this from other changes in main which will not be included in 0.4.X?
